define(['app'],function(app){
    app.constant("dataDicts",{
            alertTitle:"离线随访",
            street:[],
            dictResident:[],
            dictDoctor:[],
            archstatus:[
                {id:"HR270_1",text:"临时档案"},
                {id:"HR270_2",text:"活动"},
                {id:"HR270_3",text:"死亡"},
                {id:"HR270_4",text:"终止"}],
            dictTgov:[],
            bloodtype : [//血型
                {id:"HR262_11",text:"A型"},
                {id:"HR262_12",text:"B型"},
                {id:"HR262_13",text:"AB型"},
                {id:"HR262_14",text:"O型"},
                {id:"HR262_15",text:"不详"}],
           bloodRH: [
                {id:"arch_rh_1",text:"否"},
                {id:"arch_rh_2",text:"是"},
                {id:"arch_rh_3",text:"不详"}],
           residenttype:[
                {id:"arch_czlx_1",text:"户籍"},
                {id:"arch_czlx_2",text:"非户籍"}],
           nation:[
                {id:"HR264_01",text:"汉族"},
                {id:"HR264_02",text:"蒙古族"},
                {id:"HR264_03",text:"回族"},
                {id:"HR264_04",text:"藏族"},
                {id:"HR264_05",text:"维吾尔族"},
                {id:"HR264_06",text:"苗族"},
                {id:"HR264_09",text:"其他"},
                {id:"HR264_10",text:"满族"},
                {id:"HR264_11",text:"朝鲜族"}],
           education:[
                {id:"HR206_1",text:"文盲或半文盲"},
                {id:"HR206_2",text:"小学"},
                {id:"HR206_3",text:"初中"},
                {id:"HR206_4",text:"高中/技校/中专"},
                {id:"HR206_5",text:"大学专科及以上"},
                {id:"HR206_6",text:"不详"}],
           vocation:[
                {id:"HR265_1",text:"国家机关、党群组织、企业、事业单位负责人"},
                {id:"HR265_2",text:"军人"},
                {id:"HR265_3",text:"专业技术人员"},
                {id:"HR265_4",text:"学生"},
                {id:"HR265_5",text:"办事人员和有关人员"},
                {id:"HR265_6",text:"商业、服务业人员"},
                {id:"HR265_7",text:"农、林、牧、渔、水利业生产人员"},
                {id:"HR265_8",text:"生产、运输设备操作人员及有关人员"},
                {id:"HR265_9",text:"不便分类的其他从业人员"},
                {id:"HR265_10",text:"失业(含待业及无业人员)"}],
           marriage:[
                {id:"HR263_1",text:"未婚"},
                {id:"HR263_2",text:"已婚"},
                {id:"HR263_3",text:"丧偶"},
                {id:"HR263_4",text:"离婚"},
                {id:"HR263_5",text:"未说明的婚姻状况"}],
           medicaretype:[
                {id:"medicare_type_1",text:"低保人群"},
                {id:"medicare_type_2",text:"五保户"},
                {id:"medicare_type_3",text:"三无人员"},
                {id:"medicare_type_4",text:"困难人员"}],
            visitway:[
                    {"id":"HR424_1","text":"门诊"},
                    {"id":"HR424_2","text":"家庭"},
                    {"id":"HR424_3","text":"电话"},
                    {"id":"HR424_4","text":"集体"},
                    {"id":"HR424_5","text":"其他"}
            ],
            saltIntake:[
                    {"id":"HR382_1","text":"轻"},
                    {"id":"HR382_2","text":"中"},
                    {"id":"HR382_3","text":"重"}
            ],
            psychology:[
                    {"id":"HR421_1","text":"良好"},
                    {"id":"HR421_2","text":"一般"},
                    {"id":"HR421_3","text":"差"}
            ],
            usedrug:[
                    {"id":"HR418_1","text":"规律服药"},
                    {"id":"HR418_2","text":"间断服药"},
                    {"id":"HR418_3","text":"不服药"}
            ],
            haved:[
                    {"id":"HR397_0","text":"无"},
                    {"id":"HR397_1","text":"有"}
            ],
            footDorsum:[
                   {"id":"HR532_1","text":"未触及"},
                   {"id":"HR532_2","text":"触及"}
                   ],
            controls:[
                    {"id":"HR423_1","text":"控制满意"},
                    {"id":"HR423_2","text":"控制不满意"},
                    {"id":"HR423_3","text":"不良反应"},
                    {"id":"HR423_4","text":"并发症"}
            ],
            lowsugarreaction:[
  					{"id":"HR531_1","text":"无"},
  					{"id":"HR531_2","text":"偶尔"},
  					{"id":"HR531_3","text":"频繁"}
            ],
            exerciseFrequency:[
					{"id":"HR409_1","text":"每天"},
					{"id":"HR409_2","text":"每周一次以上"},
					{"id":"HR409_3","text":"偶尔"},
					{"id":"HR409_4","text":"不锻炼"}
			],
			smokeFrequency:[
	                {"id":"HR403_1","text":"从不吸烟"},
	                {"id":"HR403_2","text":"已戒烟"},
	                {"id":"HR403_3","text":"吸烟"}
            ],
            wineFrequency:[
                    {"id":"HR404_1","text":"从不"},
                    {"id":"HR404_2","text":"偶尔"},
                    {"id":"HR404_3","text":"经常"},
                    {"id":"HR404_4","text":"每天"}
            ],
    	    wineRefrain:[
                    {"id":"HR406_1","text":"未戒酒"},
                    {"id":"HR406_2","text":"已戒酒"}
            ],
    	    isstoned:[
                 	{"id":"HR396_0","text":"否"},
                 	{"id":"HR396_1","text":"是"}
            ],
		    lip:[
			        {"id":"arch_kc_1","text":"红润"},
			        {"id":"arch_kc_2","text":"苍白"},
			        {"id":"arch_kc_3","text":"发绀"},
			        {"id":"arch_kc_4","text":"皲裂"},
			        {"id":"arch_kc_5","text":"疱疹"}
            ],
		    isnormal:[
		           	{"id":"HR438_001","text":"正常"},
		           	{"id":"HR438_002","text":"异常"}
		    ],    
    		yanbu:[
    		       	{"id":"arch_yb_1","text":"无充血"},
    		       	{"id":"arch_yb_2","text":"充血"},
    		       	{"id":"arch_yb_3","text":"淋巴滤泡增生"}
            ],    
    		audition:[
	                {"id":"arch_tl_1","text":"听见"},
	                {"id":"arch_tl_2","text":"听不清或无法听见"}
            ],    
            sportfun:[
                    {"id":"arch_ydgn_1","text":"可顺利完成"},
                    {"id":"arch_ydgn_2","text":"无法独立完成其中任何一个动作"}
            ],    
        	skin:[
        	      	{"id":"HR458_1","text":"正常"},
        	      	{"id":"HR458_2","text":"潮红"},
        	      	{"id":"HR458_3","text":"苍白"},
        	      	{"id":"HR458_4","text":"发绀"},
        	      	{"id":"HR458_5","text":"黄染"},
        	      	{"id":"HR458_6","text":"色素沉着"},
        	      	{"id":"HR458_7","text":"其他"}
	      	],    
		    gongmo:[
		          {"id":"arch_gm_1","text":"正常"},
		          {"id":"arch_gm_2","text":"黄染"},
		          {"id":"arch_gm_3","text":"充血"},
		          {"id":"arch_gm_4","text":"其他"}
           ],    
		    lymph:[
		            {"id":"HR457_1","text":"未触及"},
		            {"id":"HR457_2","text":"锁骨上"},
		            {"id":"HR457_3","text":"腋窝"},
		            {"id":"HR457_4","text":"其他"}
            ],    
		    luoyin:[
		           {"id":"arch_luoyin_1","text":"未触及"},
		           {"id":"arch_luoyin_2","text":"锁骨上"},
		           {"id":"arch_luoyin_3","text":"腋窝"},
		           {"id":"arch_luoyin_4","text":"其他"}
           ],    
		    xinlv:[
		            {"id":"arch_xinlv_1","text":"齐"},
		            {"id":"arch_xinlv_2","text":"不齐"},
		            {"id":"arch_xinlv_3","text":"绝对不齐"}
            ],    
		    xzsz:[
		           {"id":"arch_xzsz_1","text":"无"},
		           {"id":"arch_xzsz_2","text":"单侧"},
		           {"id":"arch_xzsz_3","text":"双侧不对称"},
		           {"id":"arch_xzsz_4","text":"双侧对称"}
            ],    
		    zbdmbd:[
		          {"id":"arch_zbdmbd_1","text":"未触及"},
		          {"id":"arch_zbdmbd_2","text":"触及左侧弱或消失"},
		          {"id":"arch_zbdmbd_3","text":"触及右侧弱或消失"},
		          {"id":"arch_zbdmbd_4","text":"触及双侧对称"}
            ],    
            gmzz:[
		            {"id":"HR456_1","text":"未及异常"},
		            {"id":"HR456_2","text":"触痛"},
		            {"id":"HR456_3","text":"包块"},
		            {"id":"HR456_4","text":"前列腺异常"},
		            {"id":"HR456_5","text":"其他"}
            ],    
		    pandn:[
		          {"id":"HR439_001","text":"阴性"},
		          {"id":"HR439_002","text":"阳性"},
		          {"id":"HR439_003","text":"不详"}
            ],
            zytz_phz:[
 		          {"id":"HR552_1","text":"是"},
 		          {"id":"HR552_2","text":"基本是"},
 		          {"id":"HR552_0","text":"否"}
            ],
            zytz_gg:[
 		          {"id":"HR553_1","text":"是"},
 		          {"id":"HR553_2","text":"倾向是"},
 		          {"id":"HR553_0","text":"否"}
            ],
            healthassess:[
		          {"id":"arch_jkpj_1","text":"体检无异常"},
		          {"id":"arch_jkpj_2","text":"有异常"}
            ],
            poisontype:[
                  {"id":"poisontype_1","text":"粉尘"},
                  {"id":"poisontype_2","text":"放射物质"},
                  {"id":"poisontype_3","text":"物理因素"},
                  {"id":"poisontype_4","text":"化学物质"},
                  {"id":"poisontype_5","text":"其他"}
            ],
            drugFrequency:[
	                {"id":"yypl_1","text":"每日一次（qd）"},
	                {"id":"yypl_2","text":"每日两次（bid）"},
	                {"id":"yypl_3","text":"每日三次（tid）"},
	                {"id":"yypl_4","text":"每日四次（qid）"},
	                {"id":"yypl_5","text":"每晚睡前一次（qn）"},
	                {"id":"yypl_6","text":"每半小时一次（q1/2h）"},
	                {"id":"yypl_7","text":"每小时一次（qh）"},
	                {"id":"yypl_8","text":"每两小时一次（q2h）"},
	                {"id":"yypl_9","text":"每三小时一次（q3h）"},
	                {"id":"yypl_10","text":"每四小时一次（q4h）"},
	                {"id":"yypl_11","text":"每六小时一次（q6h）"},
	                {"id":"yypl_12","text":"每八小时一次（q8h）"},
	                {"id":"yypl_13","text":"每十二小时一次（q12h）"},
	                {"id":"yypl_14","text":"隔天一次（qod）"},
	                {"id":"yypl_15","text":"必要时一次（prn）"},
	                {"id":"yypl_16","text":"需要时一次（sos）"},
	                {"id":"yypl_17","text":"一周一次（qw）"},
	                {"id":"yypl_18","text":"一周两次（biw）"},
	                {"id":"yypl_19","text":"一周三次（tiw）"},
	                {"id":"yypl_20","text":"饭前一次（ac）"},
	                {"id":"yypl_21","text":"饭后一次（pc）"},
	                {"id":"yypl_22","text":"临睡前一次（hs）"},
	                {"id":"yypl_23","text":"上午一次（am）"},
	                {"id":"yypl_24","text":"下午一次（pm）"}
            ],
            drugUsage:[
                   {"id":"HR383_1","text":"口服"},
                   {"id":"HR383_2","text":"注射"},
                   {"id":"HR383_3","text":"外用"},
                   {"id":"HR383_4","text":"其它"},
                   {"id":"HR383_5","text":"肌肉注射"},
                   {"id":"HR383_6","text":"皮下注射"},
                   {"id":"HR383_7","text":"皮试"},
                   {"id":"HR383_8","text":"静脉点滴"},
                   {"id":"HR383_9","text":"壶入"},
                   {"id":"HR383_10","text":"滴眼"},
                   {"id":"HR383_11","text":"含服"},
                   {"id":"HR383_12","text":"水煎服"},
                   {"id":"HR383_13","text":"外洗"},
                   {"id":"HR383_14","text":"喷服"},
                   {"id":"HR383_15","text":"代茶饮"},
                   {"id":"HR383_16","text":"即刻"}
           ],
           drugDosage:[
                  {"id":"HR390_1","text":"瓶"},
                  {"id":"HR390_2","text":"袋"},
                  {"id":"HR390_3","text":"盒"},
                  {"id":"HR390_4","text":"SL瓶"},
                  {"id":"HR390_5","text":"粒"},
                  {"id":"HR390_6","text":"片"},
                  {"id":"HR390_7","text":"贴"},
                  {"id":"HR390_8","text":"丸"},
                  {"id":"HR390_9","text":"张"},
                  {"id":"HR390_10","text":"支"},
                  {"id":"HR390_11","text":"包"},
                  {"id":"HR390_12","text":"枚"},
                  {"id":"HR390_13","text":"板"},
                  {"id":"HR390_14","text":"箱"},
                  {"id":"HR390_15","text":"个"},
                  {"id":"HR390_16","text":"块"},
                  {"id":"HR390_17","text":"条"},
                  {"id":"HR390_18","text":"轴"},
                  {"id":"HR390_19","text":"份"},
                  {"id":"HR390_20","text":"卷"},
                  {"id":"HR390_21","text":"桶"},
                  {"id":"HR390_22","text":"桶"},
                  {"id":"HR390_23","text":"桶"},
                  {"id":"HR390_24","text":"塑袋"},
                  {"id":"HR390_25","text":"g"},
                  {"id":"HR390_26","text":"mg"},
                  {"id":"HR390_27","text":"kg"},
                  {"id":"HR390_28","text":"ml"},
                  {"id":"HR390_29","text":"l"},
                  {"id":"HR390_30","text":"iu"},
                  {"id":"HR390_31","text":"万iu"},
                  {"id":"HR390_32","text":"具"},
                  {"id":"HR390_33","text":"ug"},
                  {"id":"HR390_34","text":"s"},
                  {"id":"HR390_35","text":"as"},
                  {"id":"HR390_36","text":"掀"}
          ],
          compliance:[
           		  {"id":"arch_fyycx_1","text":"规律"},
           		  {"id":"arch_fyycx_2","text":"间断"},
           		  {"id":"arch_fyycx_3","text":"不服药"}
          ],
          drugRange:[
                  {"id":"1","text":"年"},
                  {"id":"2","text":"月"},
                  {"id":"3","text":"日"}
          ],
          drugName:[
                 {"id":"1","text":"硝苯地平"},
                 {"id":"2","text":"肠溶阿司匹林片"},
                 {"id":"3","text":"依那普利"},
                 {"id":"4","text":"吲达帕胺"},
                 {"id":"5","text":"美托洛尔"},
                 {"id":"6","text":"卡托普利"},
                 {"id":"7","text":"利血平"},
                 {"id":"8","text":"复方地巴唑氢氯噻嗪胶囊"},
                 {"id":"9","text":"复方硫酸双肼屈嗪"},
                 {"id":"10","text":"尼群地平片"},
                 {"id":"11","text":"复方降压片"},
                 {"id":"12","text":"罗格列酮"},
                 {"id":"13","text":"阿卡波糖"},
                 {"id":"14","text":"格列美脲"},
                 {"id":"15","text":"格列齐特"},
                 {"id":"16","text":"格列吡嗪"},
                 {"id":"17","text":"格列本脲"},
                 {"id":"18","text":"二甲双胍"}
         ],
         insight:[
                 {"id":"HR484_1","text":"自知力完全"},
                 {"id":"HR484_2","text":"自知力不全"},
                 {"id":"HR484_3","text":"自知力缺失"}
         ],
         grade:[
			     {"id":"HR486_1","text":"良好"},
			     {"id":"HR486_2","text":"一般"},
			     {"id":"HR486_3","text":"较差"}
		 ],
		 workGrade:[
		        {"id":"scldjgz_1","text":"良好"},
		        {"id":"scldjgz_2","text":"一般"},
		        {"id":"scldjgz_3","text":"较差"},
		        {"id":"scldjgz_4","text":"此项不适用"}
         ],
         hospitalcn:[
                {"id":"hospitalcn_1","text":"从未住院"},
                {"id":"hospitalcn_2","text":"目前正在住院"},
                {"id":"hospitalcn_3","text":"既往住院，现未住院"}
         ],
         gsqk:[
                 {"id":"HR541_1","text":"无关锁"},
                 {"id":"HR541_2","text":"关锁"},
                 {"id":"HR541_3","text":"关锁已解除"}
         ],
         zlxg:[
               {"id":"dis_zlxg_1","text":"痊愈"},
               {"id":"dis_zlxg_2","text":"好转"},
               {"id":"dis_zlxg_3","text":"无变化"},
               {"id":"dis_zlxg_4","text":"加重"}
         ],
         czsf:[
               {"id":"dis_czsf_1","text":"稳定"},
               {"id":"dis_czsf_2","text":"基本稳定"},
               {"id":"dis_czsf_3","text":"不稳定"},
               {"id":"dis_czsf_4","text":"未访到"}
         ],
         babyProject:[
                {"id":"kid_db_oneold_1","text":"满月"},
                {"id":"kid_db_oneold_2","text":"2月龄"},
                {"id":"kid_db_oneold_3","text":"3月龄"},
                {"id":"kid_db_oneold_4","text":"4月龄"},
                {"id":"kid_db_oneold_5","text":"5月龄"},
                {"id":"kid_db_oneold_6","text":"6月龄"},
                {"id":"kid_db_oneold_7","text":"7月龄"},
                {"id":"kid_db_oneold_8","text":"8月龄"},
                {"id":"kid_db_oneold_9","text":"9月龄"},
                {"id":"kid_db_oneold_10","text":"10月龄"},
                {"id":"kid_db_oneold_11","text":"11月龄"}
         ],
         babyProjecttwo:[
                      {"id":"kid_db_twoold_1","text":"12月龄(1岁)"},
                      {"id":"kid_db_twoold_2","text":"18月龄(1.5岁)"},
                      {"id":"kid_db_twoold_3","text":"24月龄(2岁)"},
                      {"id":"kid_db_twoold_4","text":"30月龄(2.5岁)"},
                      {"id":"kid_db_twoold_5","text":"36月龄(3岁整)"},
                      {"id":"kid_db_twoold_13","text":"13月龄"},
                      {"id":"kid_db_twoold_14","text":"14月龄"},
                      {"id":"kid_db_twoold_15","text":"15月龄"},
                      {"id":"kid_db_twoold_16","text":"16月龄"},
                      {"id":"kid_db_twoold_17","text":"17月龄"},
                      {"id":"kid_db_twoold_19","text":"19月龄"},
                      {"id":"kid_db_twoold_20","text":"20月龄"},
                      {"id":"kid_db_twoold_21","text":"21月龄"},
                      {"id":"kid_db_twoold_22","text":"22月龄"},
                      {"id":"kid_db_twoold_23","text":"23月龄"},
                      {"id":"kid_db_twoold_25","text":"25月龄"},
                      {"id":"kid_db_twoold_26","text":"26月龄"},
                      {"id":"kid_db_twoold_27","text":"27月龄"},
                      {"id":"kid_db_twoold_28","text":"28月龄"},
                      {"id":"kid_db_twoold_29","text":"29月龄"},
                      {"id":"kid_db_twoold_31","text":"31月龄"},
                      {"id":"kid_db_twoold_32","text":"32月龄"},
                      {"id":"kid_db_twoold_33","text":"33月龄"},
                      {"id":"kid_db_twoold_34","text":"34月龄"},
                      {"id":"kid_db_twoold_35","text":"35月龄"}
                      
               ],
         babyProject2:[
                      {"id":"HR123_1","text":"3岁"},
                      {"id":"HR123_2","text":"4岁"},
                      {"id":"HR123_3","text":"5岁"},
                      {"id":"HR123_4","text":"6岁"},
                      {"id":"HR123_5","text":"7岁"},
                      {"id":"HR123_6","text":"8岁"},
                      {"id":"HR123_7","text":"9岁"},
                      {"id":"HR123_8","text":"10岁"},
                      {"id":"HR123_9","text":"11岁"},
                      {"id":"HR123_10","text":"12岁"},
                      {"id":"HR123_11","text":"13岁"}
               ],
         babyBodylevel:[
                      {"id":"bodylevel_0","text":"上等"},
                      {"id":"bodylevel_1","text":"中上等"},
                      {"id":"bodylevel_2","text":"中等"},
                      {"id":"bodylevel_3","text":"中下等"},
                      {"id":"bodylevel_4","text":"下等"}
         ],
         facecolor:[
                        {"id":"kid_db_facecolor_1","text":"红润"},
                        {"id":"kid_db_facecolor_2","text":"黄染"},
                        {"id":"kid_db_facecolor_3","text":"其他"}
         ],
         facecolor2:[//面色
                    {"id":"HR549_1","text":"红润"},
                    {"id":"HR549_2","text":"异常"}
          ],
         publicstatus:[
               {"id":"HR522_1","text":"未见异常"},
               {"id":"HR522_2","text":"异常"}
         ],
         anteriorcranialstaten:[
                  {"id":"kid_db_ql_1","text":"闭合"},
                  {"id":"kid_db_ql_2","text":"未闭"}
         ],
         hearing:[
                  {"id":"HR622_1","text":"左耳通过"},
                  {"id":"HR622_2","text":"右耳通过"},
                  {"id":"HR622_3","text":"双耳通过"},
                  {"id":"HR622_4","text":"未通过"}
         ],
         betweenvisit:[
                  {"id":"HR535_1","text":"无"},
                  {"id":"HR535_2","text":"有"},
                  {"id":"HR535_9","text":"不详"}
         ],
         eyesight:[
                  {"id":"kid_db_tgbz_1","text":"通过"},
                  {"id":"kid_db_tgbz_2","text":"未过"}
         ],
         bodygrowthstate:[//体格发育评价
                          {"id":"HR548_1","text":"正常"},
                          {"id":"HR548_2","text":"低体重"},
                          {"id":"HR548_3","text":"消瘦"},
                          {"id":"HR548_4","text":"发育迟缓"},
                          {"id":"HR548_5","text":"超重"}
          ],
          menstrualflow:[//月经量
				{"id":"period_amount_0","text":"中"},
				{"id":"period_amount_1","text":"多"},
				{"id":"period_amount_2","text":"少"}           
          ],
          dysmenorrhea:[//痛经
                {"id":"HR605_1","text":"无"},
        		{"id":"HR605_2","text":"轻度"},
        		{"id":"HR605_3","text":"中"}
          ],
          yesuan:[//增补叶酸
                {"id":"lady_yesuan_0","text":"未服用"},
          		{"id":"lady_yesuan_1","text":"已服用"}
          ],
          earlypreg:[//孕早期
     			{"id":"LADY_EARLYPREG_1","text":"无"},
    			{"id":"LADY_EARLYPREG_2","text":"病毒感染"},
    			{"id":"LADY_EARLYPREG_3","text":"风疹"}, 
     			{"id":"LADY_EARLYPREG_4","text":"服药"}
          ],
          dealresult:[//产后42天-处理
                {"id":"lady_42visit_deal_1","text":"结案"},
                {"id":"lady_42visit_deal_2","text":"转诊"}
          ],
          fenlei:[//产后42天-分类
	            {"id":"lady_42days_hf_1","text":"已恢复"},
	            {"id":"lady_42days_hf_2","text":"未恢复"}
          ],
          careadvice:[//产后42天-指导
                {"id":"lady_zhidao_42visit_1","text":"性保健"},
                {"id":"lady_zhidao_42visit_2","text":"避孕"},
                {"id":"lady_zhidao_42visit_3","text":"婴儿喂养与营养"},
                {"id":"lady_zhidao_42visit_4","text":"其他"}
          ],
          upgrowth:[//发育
          		{"id":"HR561_1","text":"正常"},
         		{"id":"HR561_2","text":"畸形"}
          ],
          pabulum:[//营养
          		{"id":"HR562_1","text":"良好"},
          		{"id":"HR562_2","text":"中"},
         		{"id":"HR562_3","text":"不良"}
          ],
          dropsy:[//浮肿
         		{"id":"HR563_1","text":"-"},
         		{"id":"HR563_2","text":"+"},
         		{"id":"HR563_3","text":"++"},
         		{"id":"HR563_4","text":"+++"},
        		{"id":"HR563_5","text":"++++"}
         ],
         antigen:[//抗原、抗体
      			{"id":"HR563_4","text":"-"},
      			{"id":"HR563_3","text":"+"},
      			{"id":"HR563_2","text":"++"},
      			{"id":"HR563_1","text":"+++"}
      	 ],
      	greekNumerals:[//希腊数字
        		{"id":"HR587_1","text":"Ⅰ度"},
        		{"id":"HR587_2","text":"Ⅱ度"},
        		{"id":"HR587_3","text":"Ⅲ度"},
        		{"id":"HR587_4","text":"Ⅳ度 "}
         ],
         finalmark:[//结案标志
           		{"id":"lady_ja_1","text":"已结案"},
           		{"id":"lady_ja_2","text":"未结案"}
         ],
         fetalmove:[//产前检查-胎动
           		{"id":"YCFTD_1","text":"良好"},
           		{"id":"YCFTD_2","text":"减少"},
           		{"id":"YCFTD_3","text":"频繁"}
         ],
         albuminuria:[//尿蛋白
            	{"id":"plusminus4_1","text":"+++"},
				{"id":"plusminus4_2","text":"++"},
				{"id":"plusminus4_3","text":"+"},
				{"id":"plusminus4_4","text":"-"}
         ],      
         feedmode:[//喂养方式
                {"id":"HR523_1","text":"纯母乳喂养"},
                {"id":"HR523_2","text":"混合喂养"},
                {"id":"HR523_3","text":"人工喂养"}
         ],
         anteriorshape:[//前颅外观
                   {"id":"kid_db_qlwg_1","text":"正常"},
                   {"id":"kid_db_qlwg_2","text":"膨隆"},
                   {"id":"kid_db_qlwg_3","text":"凹陷"},
                   {"id":"kid_db_qlwg_4","text":"其他"}
          ],
          stool:[//大便
                 {"id":"HR987_1","text":"糊状"},
                 {"id":"HR987_2","text":"稀"}
          ],
          umbilical:[//脐带
                 {"id":"kid_db_umbilical_1","text":"未脱"},
                 {"id":"kid_db_umbilical_2","text":"脱落"},
                 {"id":"kid_db_umbilical_3","text":"脐部有渗出"},
                 {"id":"kid_db_umbilical_4","text":"其他"}
          ],
          jaundice:[//黄疸部位
                     {"id":"HR988_1","text":"面部"},
                     {"id":"HR988_2","text":"躯干"},
                     {"id":"HR988_3","text":"四肢"},
                     {"id":"HR988_4","text":"手足"}
          ],
          skintwo:[//儿童首次随访皮肤
                    {"id":"kid_db_skin_1","text":"未见异常"},
                    {"id":"kid_db_skin_2","text":"湿疹"},
                    {"id":"kid_db_skin_3","text":"糜烂"},
                    {"id":"kid_db_skin_4","text":"其他"}
          ],
          regress:[//转归情况
                   {"id":"HR399_1","text":"痊愈"},
                   {"id":"HR399_2","text":"好转"},
                   {"id":"HR399_3","text":"未愈"}
          ],
          industry:[//行业类别
                    {"id":"class1_1","text":"餐饮行业"},
                    {"id":"class1_2","text":"职业卫生"},
                    {"id":"class1_3","text":"生活饮用水"},
                    {"id":"class1_4","text":"学校\/托幼机构"},
                    {"id":"class1_5","text":"医疗卫生"},
                    {"id":"class1_6","text":"公共场所"},
                    {"id":"class1_7","text":"放射卫生"}     
          ],
          industryT:[//行业分类
                     {"id":"HR598_1","text":"宾馆"},
                     {"id":"HR598_2","text":" 100㎡以上饭馆"},
                     {"id":"HR598_3","text":" 旅店"},
                     {"id":"HR598_4","text":"招待所"},
                     {"id":"HR598_5","text":"咖啡馆"},
                     {"id":"HR598_6","text":" 酒吧"},
                     {"id":"HR598_7","text":"茶座"},
                     {"id":"HR598_8","text":"公共浴室"},
                     {"id":"HR598_9","text":"理发店"},
                     {"id":"HR598_10","text":"美容店"},
                     {"id":"HR598_11","text":" 影剧院"},
                     {"id":"HR598_12","text":"录像厅（室）"},
                     {"id":"HR598_13","text":"游艺厅（室）"},
                     {"id":"HR598_14","text":"舞厅"},
                     {"id":"HR598_15","text":" 音乐厅"},
                     {"id":"HR598_16","text":" 体育场（馆）"},
                     {"id":"HR598_17","text":" 游泳场（馆）"},
                     {"id":"HR598_18","text":"展览馆"},
                     {"id":"HR598_19","text":"博物馆"},
                     {"id":"HR598_20","text":" 美术馆"},
                     {"id":"HR598_21","text":"图书馆"},
                     {"id":"HR598_22","text":"商场（店）"},
                     {"id":"HR598_23","text":"书店"},
                     {"id":"HR598_24","text":"候车（机、船）室"},
                     {"id":"HR598_25","text":"公共交通工具"}   
          ],
          patroltype:[//巡查类别
                    {"id":"HR578_2","text":"协同巡查"},
                    {"id":"HR578_1","text":"自主巡查"}  
          ],
         gender:[
                  {"id":"HR481_1","text":"男"},
                  {"id":"HR481_2","text":"女"}
         ],
         clinictype:[
                  {"id":"1","text":"初诊"},
                  {"id":"2","text":"复诊"}
         ],
          edutype:[
                   {"id":"HR510_1","text":"发放印刷资料"},
                   {"id":"HR510_3","text":"个体化健康教育"},
                   {"id":"HR510_4","text":"健康知识讲座"},
                   {"id":"HR510_5","text":"公众宣传活动"},
                   {"id":"HR510_6","text":"播放音像资料"}
          ],
          eduobject:[
                     {"id":"HR511_1","text":"辖区居民"},
                     {"id":"HR511_2","text":"幼儿园"},
                     {"id":"HR511_3","text":"学校"},
                     {"id":"HR511_4","text":"集体单位"},
                     {"id":"HR511_5","text":"其它"}
          ],
          publicitytype:[
                         {"id":"ptype_1","text":"传染病"},
                         {"id":"ptype_2","text":"慢性病"},
                         {"id":"ptype_3","text":"食品卫生"},
                         {"id":"ptype_4","text":"职业卫生"},
                         {"id":"ptype_5","text":"结核病"},
                         {"id":"ptype_6","text":"艾滋病"},
                         {"id":"ptype_7","text":"其它"}
          ],
          category:[
                         {"id":"rqfl_1","text":"高血压患者"},
                         {"id":"rqfl_2","text":"糖尿病患者"},
                         {"id":"rqfl_3","text":"孕产妇"},
                         {"id":"rqfl_4","text":"育龄妇女"},
                         {"id":"rqfl_5","text":"儿童"},
                         {"id":"rqfl_6","text":"老年人"},
                         {"id":"rqfl_9","text":"其它"}
          ],
          checkresult:[
                         {"id":"JKJY_CHECKRESULT_1","text":"合格"},
                         {"id":"JKJY_CHECKRESULT_2","text":"不合格"},
                         {"id":"JKJY_CHECKRESULT_3","text":"整改"}
          ],
          oldthink:[
                       {"id":"satisfied_1","text":"满意"},
                       {"id":"satisfied_2","text":"基本满意"},
                       {"id":"satisfied_3","text":"说不清楚"},
                       {"id":"satisfied_4","text":"不太满意"},
                       {"id":"satisfied_5","text":"不满意"}
          ],
          oldkown:[
                       {"id":"arch_csyyx_1","text":"粗筛阴性"},
                       {"id":"arch_csyyx_2","text":"粗筛阳性"}
          ],
          oldselfcare:[
                       {"id":"ARCH_OLDSELFCARE_1","text":"可自理"},
                       {"id":"ARCH_OLDSELFCARE_2","text":"轻度依赖"},
                       {"id":"ARCH_OLDSELFCARE_3","text":"中度依赖"},
                       {"id":"ARCH_OLDSELFCARE_4","text":"不能自理"}
          ],
         vocation1:[
					{id:"HR512_1",text:"幼托儿童"},
					{id:"HR512_2",text:"散居儿童"},
					{id:"HR512_3",text:"学生（大中小学）"},
					{id:"HR512_4",text:"教师"},
					{id:"HR512_5",text:"保育员及保姆"},
					{id:"HR512_6",text:"餐饮食品业"},
					{id:"HR512_7",text:"商业服务"},
					{id:"HR512_8",text:"医务人员"},
					{id:"HR512_9",text:"工人"},
					{id:"HR512_10",text:"民工"},
					{id:"HR512_11",text:"农民"},
					{id:"HR512_12",text:"牧民"},
					{id:"HR512_13",text:"渔（船）民"},
					{id:"HR512_14",text:"干部职员"},
					{id:"HR512_15",text:"离退人员"},
					{id:"HR512_16",text:"家务及待业"},
					{id:"HR512_17",text:"其他"},
					{id:"HR512_18",text:"不详"}
         ],
         familyaddr:[
					{id:"familyaddr_1",text:"本县区"},
					{id:"familyaddr_2",text:"本市其他县区"},
					{id:"familyaddr_3",text:"本省其它地市"},
					{id:"familyaddr_4",text:"外省"},
					{id:"familyaddr_5",text:"港澳台"},
					{id:"familyaddr_6",text:"外籍"}
         ],
         casetype1:[
					{id:"casetype1_1",text:"疑似病例"},
					{id:"casetype1_2",text:"临床诊断病例"},
					{id:"casetype1_3",text:"实验室确诊病例"},
					{id:"casetype1_4",text:"病原携带者"}
         ],
         casetype2:[
					{id:"HR513_1",text:"急性"},
					{id:"HR513_2",text:"慢性(乙型肝炎、血吸虫病填写)"}
         ],
         infectioncode:[
					{id:"infectiontype_bing_1",text:"流行性感冒"},
					{id:"infectiontype_bing_10",text:"除霍乱、细菌性和阿米巴性痢疾、伤寒和副伤寒以外的感染性腹泻病"},
					{id:"infectiontype_bing_11",text:"手足口病"},
					{id:"infectiontype_bing_2",text:"流行性腮腺炎"},
					{id:"infectiontype_bing_3",text:"风疹"},
					{id:"infectiontype_bing_4",text:"急性出血性结膜炎"},
					{id:"infectiontype_bing_5",text:"麻风病"},
					{id:"infectiontype_bing_6",text:"流行性和地方性斑疹伤寒"},
					{id:"infectiontype_bing_7",text:"黑热病"},
					{id:"infectiontype_bing_8",text:"包虫病"},
					{id:"infectiontype_bing_9",text:"丝虫病"},
					{id:"infectiontype_jia_1",text:"鼠疫"},
					{id:"infectiontype_jia_2",text:"霍乱"},
					{id:"infectiontype_other_1",text:"非淋菌性尿道炎"},
					{id:"infectiontype_other_10",text:"人感染猪链球菌"},
					{id:"infectiontype_other_11",text:"人粒细胞无形体病"},
					{id:"infectiontype_other_12",text:"不明原因肺炎"},
					{id:"infectiontype_other_13",text:"不明原因"},
					{id:"infectiontype_other_14",text:"发热伴血小板减少综合症"},
					{id:"infectiontype_other_15",text:"AFP"},
					{id:"infectiontype_other_16",text:"其他"},
					{id:"infectiontype_other_2",text:"尖锐湿疣"},
					{id:"infectiontype_other_3",text:"生殖器疱疹"},
					{id:"infectiontype_other_4",text:"水痘"},
					{id:"infectiontype_other_5",text:"肝吸虫病"},
					{id:"infectiontype_other_6",text:"生殖道沙眼衣原体感染"},
					{id:"infectiontype_other_7",text:"恙虫病"},
					{id:"infectiontype_other_8",text:"森林脑炎"},
					{id:"infectiontype_other_9",text:"结核性胸膜炎"},
					{id:"infectiontype_qt_1",text:"其他疾病"},
					{id:"infectiontype_yi_1",text:"传染性非典型肺炎"},
					{id:"infectiontype_yi_10",text:"脊髓灰质炎"},
					{id:"infectiontype_yi_11",text:"人感染高致病性禽流感"},
					{id:"infectiontype_yi_13",text:"麻疹"},
					{id:"infectiontype_yi_14",text:"流行性出血热"},
					{id:"infectiontype_yi_15",text:"狂犬病"},
					{id:"infectiontype_yi_16",text:"流行性乙型脑炎"},
					{id:"infectiontype_yi_17",text:"登革热"},
					{id:"infectiontype_yi_18",text:"肺炭疽"},
					{id:"infectiontype_yi_19",text:"皮肤炭疽"},
					{id:"infectiontype_yi_2",text:"艾滋病"},
					{id:"infectiontype_yi_20",text:"未分型炭疽"},
					{id:"infectiontype_yi_21",text:"细菌性痢疾"},
					{id:"infectiontype_yi_22",text:"阿米巴性痢疾"},
					{id:"infectiontype_yi_23",text:"肺结核(涂阳)"},
					{id:"infectiontype_yi_24",text:"肺结核(仅培阳)"},
					{id:"infectiontype_yi_25",text:"肺结核(菌阴)"},
					{id:"infectiontype_yi_26",text:"肺结核(未痰检)"},
					{id:"infectiontype_yi_27",text:"伤寒"},
					{id:"infectiontype_yi_28",text:"副伤寒"},
					{id:"infectiontype_yi_29",text:"流行性脑脊髓膜炎"},
					{id:"infectiontype_yi_3",text:"HIV"},
					{id:"infectiontype_yi_30",text:"百日核"},
					{id:"infectiontype_yi_31",text:"白喉"},
					{id:"infectiontype_yi_32",text:"新生儿破伤风"},
					{id:"infectiontype_yi_33",text:"猩红热"},
					{id:"infectiontype_yi_34",text:"布鲁氏菌病"},
					{id:"infectiontype_yi_35",text:"淋病"},
					{id:"infectiontype_yi_36",text:"I期梅毒"},
					{id:"infectiontype_yi_37",text:"II期梅毒"},
					{id:"infectiontype_yi_38",text:"III期梅毒"},
					{id:"infectiontype_yi_39",text:"胎传梅毒"},
					{id:"infectiontype_yi_4",text:"人感染H7N9禽流感"},
					{id:"infectiontype_yi_40",text:"隐性梅毒"},
					{id:"infectiontype_yi_41",text:"钩端螺旋体病"},
					{id:"infectiontype_yi_42",text:"血吸虫病"},
					{id:"infectiontype_yi_43",text:"间日疟"},
					{id:"infectiontype_yi_44",text:"恶性疟"},
					{id:"infectiontype_yi_45",text:"未分型疟疾"},
					{id:"infectiontype_yi_5",text:"甲型病毒性肝炎"},
					{id:"infectiontype_yi_6",text:"乙型病毒性肝炎"},
					{id:"infectiontype_yi_7",text:"丙型病毒性肝炎"},
					{id:"infectiontype_yi_8",text:"戊型病毒性肝炎"},
					{id:"infectiontype_yi_9",text:"未分型病毒性肝炎"}
         ],
         insroute:[
					{id:"insroute_10",text:"其他"},
					{id:"insroute_1",text:"注射毒品"},
					{id:"insroute_2",text:"异性传播"},
					{id:"insroute_3",text:"同性传播"},
					{id:"insroute_4",text:"性接触+注射毒品"},
					{id:"insroute_5",text:"采血（浆）"},
					{id:"insroute_6",text:"输血/血制品"},
					{id:"insroute_7",text:"母婴传播"},
					{id:"insroute_8",text:"职业暴露"},
					{id:"insroute_9",text:"不详"}
         ],
         resourcef:[
					{id:"HR624_1",text:"术前检测"},
					{id:"HR624_2",text:"受血（制品）前检测"},
					{id:"HR624_3",text:"性病门诊"},
					{id:"HR624_4",text:"其他就诊者检测"},
					{id:"HR624_5",text:"婚前检查（含涉外婚姻"},
					{id:"HR624_6",text:"孕产期检查"},
					{id:"HR624_7",text:"检测咨询"},
					{id:"HR624_8",text:"阳性者配偶或性伴检测"},
					{id:"HR624_9",text:"女性阳性者子女检测"},
					{id:"HR624_10",text:"职业暴露检测"},
					{id:"HR624_11",text:"娱乐场所人员体检"},
					{id:"HR624_12",text:"有偿供血（浆）人员检测"},
					{id:"HR624_13",text:"无偿献血人员检测"},
					{id:"HR624_14",text:"出入境人员体检"},
					{id:"HR624_15",text:"新兵体检"},
					{id:"HR624_16",text:"强制/劳教戒毒人员检测"},
					{id:"HR624_17",text:"妇教所/女劳收教人员检测"},
					{id:"HR624_18",text:"其他羁押人员体检"},
					{id:"HR624_19",text:"专题调查"},
					{id:"HR624_20",text:"其他"}
        ],
        infectiontype:[
					{id:"infectiontype_1",text:"甲类传染病"},
					{id:"infectiontype_2",text:"乙类传染病"},
					{id:"infectiontype_3",text:"丙类传染病"},
					{id:"infectiontype_4",text:"其他法定管理以及重点监测传染病"},
					{id:"infectiontype_5",text:"其他疾病"}
        ],
        limresoult:[
					{id:"HR625_1",text:"确认结果阳性"},
					{id:"HR625_2",text:"替代策略检测阳性"}
        ],
        reportlevel:[
                    {"id":"reportlevel_1","text":"初次报告"},
                     {"id":"reportlevel_2","text":"订正报告"}
        ]
    
        });
    
});